#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# aotg-hcd
obj-$(CONFIG_USB_AOTG_HCD) += aotg.o aotg-hcd.o
obj-$(CONFIG_AOTG_NEW_MODE) += aotg-ring.o
