#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += pinmux_ats3605.o
obj-y += clk_ats3605.o
obj-y += timer_ats3605.o
obj-y += dram.o
obj-$(CONFIG_ATS3605_BOOTPARA) += bootpara_ats3605.o
obj-$(CONFIG_HARD_POWERKEY) += hard_powerkey.o
